@echo off
setlocal
cd /d "%~dp0.."
echo [1/5] Installing npm dependencies...
call npm install || exit /b 1
echo [2/5] Generating Prisma client...
call npm run db:generate || exit /b 1
echo [3/5] Creating SQLite database...
call npm run db:push || exit /b 1
echo [4/5] Seeding database...
call npm run db:seed || exit /b 1
echo [5/5] Installing Playwright browsers...
call npx playwright install chromium || echo [warn] Playwright install skipped
echo.
echo Local SQLite setup complete. Playwright browsers installed.
pause
